n = nuke.thisNode()
n['w_cChip'].setFlag(nuke.STARTLINE)
n['o_cChip'].setFlag(nuke.STARTLINE)
n['w_python_example'].setFlag(0x0000000010000000)
n['o_html_example'].setFlag(0x0000000010000000)
nuke.knobDefault("ColorPicker.w_hex", "0x347FFFF")
nuke.knobDefault("ColorPicker.w_int", "55050239")
nuke.knobDefault("ColorPicker.w_python_example", "nuke.selectedNode()['tile_color'].setValue(55050239)")
nuke.knobDefault("ColorPicker.o_hex", "#1E90FF")
nuke.knobDefault("ColorPicker.current_tile_color", "512819199")
nuke.knobDefault("ColorPicker.o_text_test", "You can enter any text you want to test ~•.•~")
nuke.knobDefault("ColorPicker.o_html_example", "<span style='color:#1E90FF'>You can enter any text you want to test ~•.•~</span>")